# -*- coding: utf-8 -*-
"""Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pllf6_qcVQfa7b915Vhmk_IQ2dIyFHbe

# Visual representations showing how South Africa's female population values are distributed over the years 1960–2023.
"""

from google.colab import drive
import pandas as pd
import matplotlib.pyplot as plt

"""**Mount Google Drive and Define file path**"""

drive.mount('/content/drive')

file_path =('/content/drive/MyDrive/API_SP.POP.TOTL.FE.IN_DS2_en_csv_v2_4459.csv')

data = pd.read_csv(file_path, skiprows =4)

"""**Extract relevant data for South Africa**"""

south_africadata = data[data['Country Name'] == 'South Africa']

years = [str(year) for year in range(1960, 2024)]  # Years as strings for column access
yearstodisplay = south_africadata[years].values.flatten()

"""**Histogram**"""

plt.figure(figsize=(10, 6))
plt.hist(yearstodisplay, bins=15, color='skyblue', edgecolor='black')
plt.title("Distribution of Female Population in South Africa (1960-2023)", fontsize=14)
plt.xlabel("Population", fontsize=12)
plt.ylabel("Frequency", fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""**Line Plot**"""

plt.figure(figsize=(12, 6))
plt.plot(years, yearstodisplay, marker='o', color='blue', linestyle='-', linewidth=2)
plt.title("Trend of Female Population in South Africa (1960-2023)", fontsize=16)
plt.xlabel("Year", fontsize=14)
plt.ylabel("Population", fontsize=14)
plt.xticks(rotation=45, fontsize=10)
plt.yticks(fontsize=10)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()